#ifndef __SESSION_H_
#define __SESSION_H_

#include "netSDK/netcomm.h"
#include "netSDK/netSDK.h"

#define	RIGHT_ADMIN		3
#define	RIGHT_USER		2
#define	RIGHT_GUEST		1

int SESSION_init();
int SESSION_destroy();

int checkUser(MSG_HEAD *pMsgHead, char *pUserName, char *pPsw);
int checkUdpUser(MSG_HEAD *pMsgHead, char *pUserName, char *pPsw, struct sockaddr_in addr);
int jpegSendBitRateFun(int nChannel, int nStreamType, void *stream, int size, int uploadType);
int recvCmdProcFun(MSG_HEAD *pMsgHead, char *pRecvBuf);

/////////////////////////////////////////////
// 设备命令的头
typedef struct
{
	unsigned long nCmdLen;		// 命令头后面的数据长度
	unsigned long nCmdID;		// 命令ID
	unsigned long nChannel;		// 针对哪一个通道，如果命令是针对系统，与通道无关，则该值为0
	unsigned long nReserve;		// 保留

} DEV_CMD_HEADER;

// 设备命令的返回
typedef struct
{
	unsigned long nCmdLen;		// 命令头后面的数据长度
	unsigned long nCmdID;		// 命令ID
	unsigned long nResult;		// 命令是否成功：0为成功，非零则为失败
	unsigned long nReserve;		// 保留

} DEV_CMD_RETURN;

/*
typedef struct _FRAME_HEAD
{
    unsigned long nFlag;
    unsigned long nVideoSize;
    unsigned long nTimeTick;
    unsigned short nAudioSize;
    unsigned char bKeyFrame;
    unsigned char Reserved;

}FRAME_HEAD, *PFRAME_HEAD;
*/

#define NETCMD_RECORD			20000

//DEV的CMD
typedef enum
{
    CMD_NOT_SUPPORT				= 0x10000,

    SET_VIDEO_STANDARD			= CMD_NOT_SUPPORT+1,
    GET_VIDEO_STANDARD			= CMD_NOT_SUPPORT+2,
    SET_VIDEO_ATTR				= CMD_NOT_SUPPORT+3,
    GET_VIDEO_ATTR				= CMD_NOT_SUPPORT+4,
    SET_VIDEO_FORMAT			= CMD_NOT_SUPPORT+5,
    GET_VIDEO_FORMAT			= CMD_NOT_SUPPORT+6,
    SET_VIDEO_ENC_TYPE			= CMD_NOT_SUPPORT+7,
    GET_VIDEO_ENC_TYPE			= CMD_NOT_SUPPORT+8,
    SET_VIDEO_ENC_PARAM			= CMD_NOT_SUPPORT+9,
    GET_VIDEO_ENC_PARAM			= CMD_NOT_SUPPORT+10,
    SET_VIDEO_MOTION_PARAM		= CMD_NOT_SUPPORT+11,
    GET_VIDEO_MOTION_PARAM		= CMD_NOT_SUPPORT+12,
    SET_VIDEO_WM_PARAM			= CMD_NOT_SUPPORT+13,
    GET_VIDEO_WM_PARAM			= CMD_NOT_SUPPORT+14,
    SET_CHANNEL_NAME			= CMD_NOT_SUPPORT+15,
    GET_CHANNEL_NAME			= CMD_NOT_SUPPORT+16,

    SET_AUDIO_IN_ATTR			= CMD_NOT_SUPPORT+21,
    GET_AUDIO_IN_ATTR			= CMD_NOT_SUPPORT+22,
    SET_AUDIO_IN_ENC_TYPE		= CMD_NOT_SUPPORT+23,
    GET_AUDIO_IN_ENC_TYPE		= CMD_NOT_SUPPORT+24,
    SET_AUDIO_IN_ENC_PARAM		= CMD_NOT_SUPPORT+25,
    GET_AUDIO_IN_ENC_PARAM		= CMD_NOT_SUPPORT+26,
    SET_AUDIO_OUT_ATTR			= CMD_NOT_SUPPORT+27,
    GET_AUDIO_OUT_ATTR			= CMD_NOT_SUPPORT+28,
    SET_AUDIO_OUT_DEC_TYPE		= CMD_NOT_SUPPORT+29,
    GET_AUDIO_OUT_DEC_TYPE		= CMD_NOT_SUPPORT+30,
    SET_AUDIO_OUT_DEC_PARAM		= CMD_NOT_SUPPORT+31,
    GET_AUDIO_OUT_DEC_PARAM		= CMD_NOT_SUPPORT+32,

    SET_VIDEO_OSD				= CMD_NOT_SUPPORT+40,
    GET_VIDEO_OSD				= CMD_NOT_SUPPORT+41,
    SET_VIDEO_MASK				= CMD_NOT_SUPPORT+42,
    GET_VIDEO_MASK				= CMD_NOT_SUPPORT+43,
    SET_VIDEO_LOGO				= CMD_NOT_SUPPORT+44,
    GET_VIDEO_LOGO				= CMD_NOT_SUPPORT+45,
    SET_VIDEO_MOSAIC			= CMD_NOT_SUPPORT+46,
    GET_VIDEO_MOSAIC			= CMD_NOT_SUPPORT+47,

    SET_MULTIDEV_INFO			= CMD_NOT_SUPPORT+48,	//设置多画面设备列表
    GET_MULTIDEV_INFO			= CMD_NOT_SUPPORT+49,	//获取多画面设备列表

    SET_VIDEO_LOST_ALARM_PARAM	= CMD_NOT_SUPPORT+60,
    GET_VIDEO_LOST_ALARM_PARAM	= CMD_NOT_SUPPORT+61,
    SET_VIDEO_MOTION_ALARM_PARAM= CMD_NOT_SUPPORT+62,
    GET_VIDEO_MOTION_ALARM_PARAM= CMD_NOT_SUPPORT+63,
    SET_PROBE_IN_ALARM_PARAM	= CMD_NOT_SUPPORT+64,
    GET_PROBE_IN_ALARM_PARAM	= CMD_NOT_SUPPORT+65,
    SET_VIDEO_MASK_ALARM_PARAM	= CMD_NOT_SUPPORT+66,
    GET_VIDEO_MASK_ALARM_PARAM	= CMD_NOT_SUPPORT+67,

    SET_IRPROBE_ALARM_PARAM		= (CMD_NOT_SUPPORT+68),	//设置红外探头报警参数
    GET_IRPROBE_ALARM_PARAM		= (CMD_NOT_SUPPORT+69),	//获取红外探头报警参数
    SET_IRPROBE_ALARM_STUDY		= (CMD_NOT_SUPPORT+70),    //红外探头学习
    SET_IRPROBE_ALARM_RESET		= (CMD_NOT_SUPPORT+71),	//红外探头重置


    SET_IRPROBE_ALARM_START		=	(CMD_NOT_SUPPORT+72),	//红外探头布防
    SET_IRPROBE_ALARM_STOP		=	(CMD_NOT_SUPPORT+73),	//红外探头撤防


    SET_PROBE_STATUS			= CMD_NOT_SUPPORT+81,
    GET_PROBE_STATUS			= CMD_NOT_SUPPORT+82,
    SET_PROBE_OUT_PARAM			= CMD_NOT_SUPPORT+83,
    GET_PROBE_OUT_PARAM			= CMD_NOT_SUPPORT+84,

    SET_NETWORK_PARAM			= CMD_NOT_SUPPORT+101,
    GET_NETWORK_PARAM			= CMD_NOT_SUPPORT+102,

    SET_REMOTE_CONNECT_PARAM	= CMD_NOT_SUPPORT+103,
    GET_REMOTE_CONNECT_PARAM	= CMD_NOT_SUPPORT+104,

    SET_WIFI_PARAM				= CMD_NOT_SUPPORT+105,
    GET_WIFI_PARAM				= CMD_NOT_SUPPORT+106,
    SCAN_WIFI_PARAM				= CMD_NOT_SUPPORT+219,

    SET_UPNP_PARAM				= 0x1006b,
    GET_UPNP_PARAM				= 0x1006c,

    SET_P2P_PARAM				= CMD_NOT_SUPPORT+109,
    GET_P2P_PARAM				= CMD_NOT_SUPPORT+110,

#ifdef LOBO
    SET_LOBO_PARAM				= CMD_NOT_SUPPORT+111,
    GET_LOBO_PARAM				= CMD_NOT_SUPPORT+112,
#endif

    SET_SYS_INFO				= CMD_NOT_SUPPORT+121,
    GET_SYS_INFO				= CMD_NOT_SUPPORT+122,

    SET_REMOTE_TALK_IP			= CMD_NOT_SUPPORT+141,
    GET_REMOTE_TALK_IP			= CMD_NOT_SUPPORT+142,

    SET_FTP_PARAM				= CMD_NOT_SUPPORT+161,
    GET_FTP_PARAM				= CMD_NOT_SUPPORT+162,
    SET_TFTP_PARAM				= CMD_NOT_SUPPORT+163,
    GET_TFTP_PARAM				= CMD_NOT_SUPPORT+164,
    SET_EMAIL_PARAM				= CMD_NOT_SUPPORT+165,
    GET_EMAIL_PARAM				= CMD_NOT_SUPPORT+166,
    SET_AUTO_SNAPSHOT_PARAM		= CMD_NOT_SUPPORT+167,
    GET_AUTO_SNAPSHOT_PARAM		= CMD_NOT_SUPPORT+168,

    SET_PPPOE_PARAM				= CMD_NOT_SUPPORT+181,
    GET_PPPOE_PARAM				= CMD_NOT_SUPPORT+182,
    SET_DDNS_PARAM				= CMD_NOT_SUPPORT+183,
    GET_DDNS_PARAM				= CMD_NOT_SUPPORT+184,

  //  SET_UPNP_PARAM				= CMD_NOT_SUPPORT+185,
  //  GET_UPNP_PARAM				= CMD_NOT_SUPPORT+186,

    SET_USER_INFO				= CMD_NOT_SUPPORT+201,
    GET_USER_INFO				= CMD_NOT_SUPPORT+202,

    SET_DEV_TIME				= CMD_NOT_SUPPORT+221,
    GET_DEV_TIME				= CMD_NOT_SUPPORT+222,

    SET_NTP_PARAM				= CMD_NOT_SUPPORT+223,
    GET_NTP_PARAM				= CMD_NOT_SUPPORT+224,

    SAVE_DEV_PARAM				= CMD_NOT_SUPPORT+241,
    RESUME_DEV_DEFAULT_PARAM	= CMD_NOT_SUPPORT+242,
    REBOOT_DEV					= CMD_NOT_SUPPORT+243,
    UPDATE_DEV					= CMD_NOT_SUPPORT+244,
    MANUAL_SNAPSHOT				= CMD_NOT_SUPPORT+245,

    SET_PTZ_CTRL_MODE			= CMD_NOT_SUPPORT+281,
    GET_PTZ_CTRL_MODE			= CMD_NOT_SUPPORT+282,
    GET_PTZ_LIST				= CMD_NOT_SUPPORT+283,
    ADD_PTZ						= CMD_NOT_SUPPORT+284,
    DELETE_PTZ					= CMD_NOT_SUPPORT+285,
    SET_CHANNEL_PTZ_PARAM		= CMD_NOT_SUPPORT+286,
    GET_CHANNEL_PTZ_PARAM		= CMD_NOT_SUPPORT+287,
    SET_RS485_COM_PARAM			= CMD_NOT_SUPPORT+288,
    GET_RS485_COM_PARAM			= CMD_NOT_SUPPORT+289,
    CTRL_PTZ					= CMD_NOT_SUPPORT+290,
    RS485_BYPASS_COM			= CMD_NOT_SUPPORT+291,
    SET_RS232_COM_PARAM			= CMD_NOT_SUPPORT+292,
    GET_RS232_COM_PARAM			= CMD_NOT_SUPPORT+293,
    RS232_BYPASS_COM			= CMD_NOT_SUPPORT+294,

    GET_BROADCAST_INFO			= CMD_NOT_SUPPORT+301,
    CONFIG_SERVER_INFO			= CMD_NOT_SUPPORT+302,

    RESUME_DEFAULT_COLOR		= CMD_NOT_SUPPORT+303,		// Add the code by lvjh, 2008-05-10
    SET_IMAGE_FLIP				= CMD_NOT_SUPPORT+304,		// Add the code by lvjh, 2008-05-10
    GET_IMAGE_FLIP				= CMD_NOT_SUPPORT+305,		// Add the code by lvjh, 2008-05-10
    SET_IMAGE_MIRROR			= CMD_NOT_SUPPORT+306,		// Add the code by lvjh, 2008-05-10
    GET_IMAGE_MIRROR			= CMD_NOT_SUPPORT+307,		// Add the code by lvjh, 2008-05-10
    SET_AUDIO_INPUT				= CMD_NOT_SUPPORT+308,		// Add the code by lvjh, 2008-05-10
    GET_AUDIO_INPUT				= CMD_NOT_SUPPORT+309,		// Add the code by lvjh, 2008-05-10
    SET_IMAGE_HZ				= CMD_NOT_SUPPORT+310,		// Add the code by lvjh, 2008-05-10
    GET_IMAGE_HZ				= CMD_NOT_SUPPORT+311,		// Add the code by lvjh, 2008-05-10

    SAVE_DEV_PARAM_FILE			= CMD_NOT_SUPPORT+312,		// Add the code by lvjh, 2010-03-03
    RESUME_DEV_PARAM_FILE		= CMD_NOT_SUPPORT+313,		// Add the code by lvjh, 2010-03-03
    GET_MT_PARAM				= CMD_NOT_SUPPORT+314,		// Add the code by lvjh, 2010-03-03
    SET_MT_PARAM				= CMD_NOT_SUPPORT+315,		// Add the code by lvjh, 2010-03-03
    RESUME_HW_DEFAULT_PARAM		= CMD_NOT_SUPPORT+316,		// Add the code by lvjh, 2010-03-03

    SET_ALARM_STATUS 			= CMD_NOT_SUPPORT+350,
    GET_ALARM_STATUS			= CMD_NOT_SUPPORT+351,
    SEND_ALARMSTATUS_PARAM		= CMD_NOT_SUPPORT+496,

    SET_TIME_REBOOT				= CMD_NOT_SUPPORT+352,
    GET_TIME_REBOOT				= CMD_NOT_SUPPORT+353,
    SET_ALL_IRALARM_STATUS		= CMD_NOT_SUPPORT+354,

    DEV_SNAPSHOT_RESULT			= (CMD_NOT_SUPPORT+497),	//手动抓拍结果
    DEV_RECORD_RESULT			= (CMD_NOT_SUPPORT+498),	//手动录像结果

    DEV_PTZ_AUTO_CTRL			= CMD_NOT_SUPPORT+499,
    DEV_TITLE_CHANGE			= CMD_NOT_SUPPORT+500,
    DEV_ALARM_INFO				= CMD_NOT_SUPPORT+501,
    DEV_NOTIFY_INFO				= CMD_NOT_SUPPORT+502,
    DEV_JPEG_DATA				= CMD_NOT_SUPPORT+503,
    DEV_TALK_REQUEST			= CMD_NOT_SUPPORT+504,
    DEV_CHN_NAME_CHANGE			= CMD_NOT_SUPPORT+505,

#ifdef MOBILE_PLATFORM
    SET_MP_INFO					= CMD_NOT_SUPPORT+506,
    GET_MP_INFO					= CMD_NOT_SUPPORT+507,
#endif

    SET_G3_PARAM				= CMD_NOT_SUPPORT+508,
    GET_G3_PARAM				= CMD_NOT_SUPPORT+509,
    SET_SCHEDULE_SNAPSHOT_PARAM	= CMD_NOT_SUPPORT+510,
    GET_SCHEDULE_SNAPSHOT_PARAM	= CMD_NOT_SUPPORT+511,
    SET_PTZ_AUTO_CTRL			= CMD_NOT_SUPPORT+512,		// Add the code by lvjh, 2006-09-16
    GET_PTZ_AUTO_CTRL			= CMD_NOT_SUPPORT+513,		// Add the code by lvjh, 2006-09-16

    SET_PLATFORM_PARAM			= CMD_NOT_SUPPORT+514,
    GET_PLATFORM_PARAM			= CMD_NOT_SUPPORT+515,

    //add the code by lvjh 2012-08-18
    SET_RTSP_PARAM				=	CMD_NOT_SUPPORT+516,
    GET_RTSP_PARAM				=	CMD_NOT_SUPPORT+517,

    //亿源ddns 命令字
    SET_YIYUAN_DDNS_PARAM		= CMD_NOT_SUPPORT+560,
    GET_YIYUAN_DDNS_PARAM		= CMD_NOT_SUPPORT+561,



    SET_DEVICE_CONFIGURE		= CMD_NOT_SUPPORT+1001,
    GET_DEVICE_CONFIGURE		= CMD_NOT_SUPPORT+1002,
    SET_CHIP_INIT				= CMD_NOT_SUPPORT+1003,		// Add the code by lvjh, 2009-11-11
    SET_CHIP_PASS				= CMD_NOT_SUPPORT+1004,		// Add the code by lvjh, 2009-11-11

#ifdef JIN_KE_GUANG
    CTRL_ROBOT					= CMD_NOT_SUPPORT+550,
#endif

#ifdef RECORD
    GET_RECORD_PARAM 			= NETCMD_RECORD+101,
    SET_RECORD_PARAM 			= NETCMD_RECORD+201,
    GET_MANUAL_RECORD_PARAM 	= NETCMD_RECORD+102,
    SET_MANUAL_RECORD_PARAM 	= NETCMD_RECORD+202,
    GET_TIMER_RECORD_PARAM 		= NETCMD_RECORD+103,
    SET_TIMER_RECORD_PARAM 		= NETCMD_RECORD+203,

    QUERY_RECORD_DATE			= NETCMD_RECORD+104,
    QUERY_RECORD_FILE			= NETCMD_RECORD+105,

    GET_RECORD_STATUS			= NETCMD_RECORD+106,
    GET_HARDDISK_INFO			= NETCMD_RECORD+107,
    GET_FDISK_PROGRESS			= NETCMD_RECORD+108,

    QUERY_JPEG_DATE				= NETCMD_RECORD+109,
    QUERY_JPEG_FILE				= NETCMD_RECORD+110,

    SET_HARDDISK_FDISK			= NETCMD_RECORD+206,
    SET_HARDDISK_FORMAT			= NETCMD_RECORD+207,

    REMOTE_RECORD_PLAYBACK		= NETCMD_RECORD+211,
    LOCAL_RECORD_PLAYBACK		= NETCMD_RECORD+212,
    REMOTE_RECORD_BACKUP		= NETCMD_RECORD+213,
    LOCAL_RECORD_BACKUP			= NETCMD_RECORD+214,
    DELETE_RECORD_FILE			= NETCMD_RECORD+215,

    REMOTE_JPEG_PLAYBACK		= NETCMD_RECORD+216,
    REMOTE_JPEG_BACKUP			= NETCMD_RECORD+217,
    DELETE_JPEG_FILE			= NETCMD_RECORD+218,




#endif
} DEV_CMD_ID;

typedef enum
{
    OPEN_RECORD_FILE				= 1,
    CLOSE_RECORD_FILE				= 2,
    READ_RECORD_FILE				= 3,
} RECORD_FILE_OPT;

#endif
