/* soapServer.c
   Generated by gSOAP 2.8.3 from onvif.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.3 2012-11-07 08:18:04 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{
			if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
#if 0
	if (!soap_match_tag(soap, soap->tag, "SOAP-ENV:Fault"))
		return soap_serve_SOAP_ENV__Fault(soap);
#endif
	if (!soap_match_tag(soap, soap->tag, "d:Probe"))
		return soap_serve___dndl__Probe(soap);
	if (!soap_match_tag(soap, soap->tag, "d:Hello"))
		return soap_serve___dnrd__Hello(soap);
	if (!soap_match_tag(soap, soap->tag, "d:Bye"))
		return soap_serve___dnrd__Bye(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

#if 0
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_SOAP_ENV__Fault(struct soap *soap)
{	struct SOAP_ENV__Fault soap_tmp_SOAP_ENV__Fault;
	soap_default_SOAP_ENV__Fault(soap, &soap_tmp_SOAP_ENV__Fault);
	soap->encodingStyle = NULL;
	if (!soap_get_SOAP_ENV__Fault(soap, &soap_tmp_SOAP_ENV__Fault, "SOAP-ENV:Fault", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = SOAP_ENV__Fault(soap, soap_tmp_SOAP_ENV__Fault.faultcode, soap_tmp_SOAP_ENV__Fault.faultstring, soap_tmp_SOAP_ENV__Fault.faultactor, soap_tmp_SOAP_ENV__Fault.detail, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Code, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Reason, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Node, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Role, soap_tmp_SOAP_ENV__Fault.SOAP_ENV__Detail);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___dndl__Probe(struct soap *soap)
{	struct __dndl__Probe soap_tmp___dndl__Probe;
	struct d__ProbeMatchesType d__ProbeMatches;
	soap_default_d__ProbeMatchesType(soap, &d__ProbeMatches);
	soap_default___dndl__Probe(soap, &soap_tmp___dndl__Probe);
	soap->encodingStyle = NULL;
	if (!soap_get___dndl__Probe(soap, &soap_tmp___dndl__Probe, "-dndl:Probe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __dndl__Probe(soap, soap_tmp___dndl__Probe.d__Probe, &d__ProbeMatches);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_d__ProbeMatchesType(soap, &d__ProbeMatches);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__ProbeMatchesType(soap, &d__ProbeMatches, "d:ProbeMatches", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__ProbeMatchesType(soap, &d__ProbeMatches, "d:ProbeMatches", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___dnrd__Hello(struct soap *soap)
{	struct __dnrd__Hello soap_tmp___dnrd__Hello;
	struct d__ResolveType dn__HelloResponse;
	soap_default_d__ResolveType(soap, &dn__HelloResponse);
	soap_default___dnrd__Hello(soap, &soap_tmp___dnrd__Hello);
	soap->encodingStyle = NULL;
	if (!soap_get___dnrd__Hello(soap, &soap_tmp___dnrd__Hello, "-dnrd:Hello", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __dnrd__Hello(soap, soap_tmp___dnrd__Hello.d__Hello, &dn__HelloResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_d__ResolveType(soap, &dn__HelloResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__ResolveType(soap, &dn__HelloResponse, "dn:HelloResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__ResolveType(soap, &dn__HelloResponse, "dn:HelloResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___dnrd__Bye(struct soap *soap)
{	struct __dnrd__Bye soap_tmp___dnrd__Bye;
	struct d__ResolveType dn__ByeResponse;
	soap_default_d__ResolveType(soap, &dn__ByeResponse);
	soap_default___dnrd__Bye(soap, &soap_tmp___dnrd__Bye);
	soap->encodingStyle = NULL;
	if (!soap_get___dnrd__Bye(soap, &soap_tmp___dnrd__Bye, "-dnrd:Bye", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __dnrd__Bye(soap, soap_tmp___dnrd__Bye.d__Bye, &dn__ByeResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_d__ResolveType(soap, &dn__ByeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__ResolveType(soap, &dn__ByeResponse, "dn:ByeResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__ResolveType(soap, &dn__ByeResponse, "dn:ByeResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
