/* soapH.h
   Generated by gSOAP 2.8.3 from onvif.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

/* _wsa__ReplyAfter is a typedef element/attribute synonym for unsignedInt */

#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
#endif

#define soap_default__wsa__ReplyAfter(soap, a) soap_default_unsignedInt(soap, a)


#define soap_out__wsa__ReplyAfter soap_out_unsignedInt


#define soap_in__wsa__ReplyAfter soap_in_unsignedInt


#ifndef soap_write__wsa__ReplyAfter
#define soap_write__wsa__ReplyAfter(soap, data) ( soap_begin_send(soap) || soap_put__wsa__ReplyAfter(soap, data, "wsa:ReplyAfter", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__ReplyAfter soap_put_unsignedInt


#ifndef soap_read__wsa__ReplyAfter
#define soap_read__wsa__ReplyAfter(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__ReplyAfter(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__ReplyAfter soap_get_unsignedInt


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef SOAP_TYPE_d__FaultCodeType
#define SOAP_TYPE_d__FaultCodeType (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__FaultCodeType(struct soap*, enum d__FaultCodeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__FaultCodeType(struct soap*, const char*, int, const enum d__FaultCodeType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_d__FaultCodeType2s(struct soap*, enum d__FaultCodeType);
SOAP_FMAC3 enum d__FaultCodeType * SOAP_FMAC4 soap_in_d__FaultCodeType(struct soap*, const char*, enum d__FaultCodeType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2d__FaultCodeType(struct soap*, const char*, enum d__FaultCodeType *);

#ifndef soap_write_d__FaultCodeType
#define soap_write_d__FaultCodeType(soap, data) ( soap_begin_send(soap) || soap_put_d__FaultCodeType(soap, data, "d:FaultCodeType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__FaultCodeType(struct soap*, const enum d__FaultCodeType *, const char*, const char*);

#ifndef soap_read_d__FaultCodeType
#define soap_read_d__FaultCodeType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__FaultCodeType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum d__FaultCodeType * SOAP_FMAC4 soap_get_d__FaultCodeType(struct soap*, enum d__FaultCodeType *, const char*, const char*);

#ifndef SOAP_TYPE_d__RelationshipType
#define SOAP_TYPE_d__RelationshipType (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__RelationshipType(struct soap*, enum d__RelationshipType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__RelationshipType(struct soap*, const char*, int, const enum d__RelationshipType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_d__RelationshipType2s(struct soap*, enum d__RelationshipType);
SOAP_FMAC3 enum d__RelationshipType * SOAP_FMAC4 soap_in_d__RelationshipType(struct soap*, const char*, enum d__RelationshipType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2d__RelationshipType(struct soap*, const char*, enum d__RelationshipType *);

#ifndef soap_write_d__RelationshipType
#define soap_write_d__RelationshipType(soap, data) ( soap_begin_send(soap) || soap_put_d__RelationshipType(soap, data, "d:RelationshipType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__RelationshipType(struct soap*, const enum d__RelationshipType *, const char*, const char*);

#ifndef soap_read_d__RelationshipType
#define soap_read_d__RelationshipType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__RelationshipType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum d__RelationshipType * SOAP_FMAC4 soap_get_d__RelationshipType(struct soap*, enum d__RelationshipType *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__FaultSubcodeValues(struct soap*, enum wsa__FaultSubcodeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__FaultSubcodeValues(struct soap*, const char*, int, const enum wsa__FaultSubcodeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_wsa__FaultSubcodeValues2s(struct soap*, enum wsa__FaultSubcodeValues);
SOAP_FMAC3 enum wsa__FaultSubcodeValues * SOAP_FMAC4 soap_in_wsa__FaultSubcodeValues(struct soap*, const char*, enum wsa__FaultSubcodeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2wsa__FaultSubcodeValues(struct soap*, const char*, enum wsa__FaultSubcodeValues *);

#ifndef soap_write_wsa__FaultSubcodeValues
#define soap_write_wsa__FaultSubcodeValues(soap, data) ( soap_begin_send(soap) || soap_put_wsa__FaultSubcodeValues(soap, data, "wsa:FaultSubcodeValues", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__FaultSubcodeValues(struct soap*, const enum wsa__FaultSubcodeValues *, const char*, const char*);

#ifndef soap_read_wsa__FaultSubcodeValues
#define soap_read_wsa__FaultSubcodeValues(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__FaultSubcodeValues(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum wsa__FaultSubcodeValues * SOAP_FMAC4 soap_get_wsa__FaultSubcodeValues(struct soap*, enum wsa__FaultSubcodeValues *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__RelationshipTypeValues(struct soap*, enum wsa__RelationshipTypeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__RelationshipTypeValues(struct soap*, const char*, int, const enum wsa__RelationshipTypeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_wsa__RelationshipTypeValues2s(struct soap*, enum wsa__RelationshipTypeValues);
SOAP_FMAC3 enum wsa__RelationshipTypeValues * SOAP_FMAC4 soap_in_wsa__RelationshipTypeValues(struct soap*, const char*, enum wsa__RelationshipTypeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2wsa__RelationshipTypeValues(struct soap*, const char*, enum wsa__RelationshipTypeValues *);

#ifndef soap_write_wsa__RelationshipTypeValues
#define soap_write_wsa__RelationshipTypeValues(soap, data) ( soap_begin_send(soap) || soap_put_wsa__RelationshipTypeValues(soap, data, "wsa:RelationshipTypeValues", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__RelationshipTypeValues(struct soap*, const enum wsa__RelationshipTypeValues *, const char*, const char*);

#ifndef soap_read_wsa__RelationshipTypeValues
#define soap_read_wsa__RelationshipTypeValues(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__RelationshipTypeValues(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum wsa__RelationshipTypeValues * SOAP_FMAC4 soap_get_wsa__RelationshipTypeValues(struct soap*, enum wsa__RelationshipTypeValues *, const char*, const char*);

#ifndef SOAP_TYPE___dnrd__Bye
#define SOAP_TYPE___dnrd__Bye (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___dnrd__Bye(struct soap*, struct __dnrd__Bye *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___dnrd__Bye(struct soap*, const struct __dnrd__Bye *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___dnrd__Bye(struct soap*, const char*, int, const struct __dnrd__Bye *, const char*);
SOAP_FMAC3 struct __dnrd__Bye * SOAP_FMAC4 soap_in___dnrd__Bye(struct soap*, const char*, struct __dnrd__Bye *, const char*);

#ifndef soap_write___dnrd__Bye
#define soap_write___dnrd__Bye(soap, data) ( soap_begin_send(soap) || (soap_serialize___dnrd__Bye(soap, data), 0) || soap_put___dnrd__Bye(soap, data, "-dnrd:Bye", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___dnrd__Bye(struct soap*, const struct __dnrd__Bye *, const char*, const char*);

#ifndef soap_read___dnrd__Bye
#define soap_read___dnrd__Bye(soap, data) ( soap_begin_recv(soap) || !soap_get___dnrd__Bye(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __dnrd__Bye * SOAP_FMAC4 soap_get___dnrd__Bye(struct soap*, struct __dnrd__Bye *, const char*, const char*);

#ifndef SOAP_TYPE___dnrd__Hello
#define SOAP_TYPE___dnrd__Hello (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___dnrd__Hello(struct soap*, struct __dnrd__Hello *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___dnrd__Hello(struct soap*, const struct __dnrd__Hello *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___dnrd__Hello(struct soap*, const char*, int, const struct __dnrd__Hello *, const char*);
SOAP_FMAC3 struct __dnrd__Hello * SOAP_FMAC4 soap_in___dnrd__Hello(struct soap*, const char*, struct __dnrd__Hello *, const char*);

#ifndef soap_write___dnrd__Hello
#define soap_write___dnrd__Hello(soap, data) ( soap_begin_send(soap) || (soap_serialize___dnrd__Hello(soap, data), 0) || soap_put___dnrd__Hello(soap, data, "-dnrd:Hello", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___dnrd__Hello(struct soap*, const struct __dnrd__Hello *, const char*, const char*);

#ifndef soap_read___dnrd__Hello
#define soap_read___dnrd__Hello(soap, data) ( soap_begin_recv(soap) || !soap_get___dnrd__Hello(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __dnrd__Hello * SOAP_FMAC4 soap_get___dnrd__Hello(struct soap*, struct __dnrd__Hello *, const char*, const char*);

#ifndef SOAP_TYPE___dndl__Probe
#define SOAP_TYPE___dndl__Probe (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___dndl__Probe(struct soap*, struct __dndl__Probe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___dndl__Probe(struct soap*, const struct __dndl__Probe *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___dndl__Probe(struct soap*, const char*, int, const struct __dndl__Probe *, const char*);
SOAP_FMAC3 struct __dndl__Probe * SOAP_FMAC4 soap_in___dndl__Probe(struct soap*, const char*, struct __dndl__Probe *, const char*);

#ifndef soap_write___dndl__Probe
#define soap_write___dndl__Probe(soap, data) ( soap_begin_send(soap) || (soap_serialize___dndl__Probe(soap, data), 0) || soap_put___dndl__Probe(soap, data, "-dndl:Probe", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___dndl__Probe(struct soap*, const struct __dndl__Probe *, const char*, const char*);

#ifndef soap_read___dndl__Probe
#define soap_read___dndl__Probe(soap, data) ( soap_begin_recv(soap) || !soap_get___dndl__Probe(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __dndl__Probe * SOAP_FMAC4 soap_get___dndl__Probe(struct soap*, struct __dndl__Probe *, const char*, const char*);

#ifndef SOAP_TYPE_d__AppSequenceType
#define SOAP_TYPE_d__AppSequenceType (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__AppSequenceType(struct soap*, struct d__AppSequenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__AppSequenceType(struct soap*, const struct d__AppSequenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__AppSequenceType(struct soap*, const char*, int, const struct d__AppSequenceType *, const char*);
SOAP_FMAC3 struct d__AppSequenceType * SOAP_FMAC4 soap_in_d__AppSequenceType(struct soap*, const char*, struct d__AppSequenceType *, const char*);

#ifndef soap_write_d__AppSequenceType
#define soap_write_d__AppSequenceType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__AppSequenceType(soap, data), 0) || soap_put_d__AppSequenceType(soap, data, "d:AppSequenceType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__AppSequenceType(struct soap*, const struct d__AppSequenceType *, const char*, const char*);

#ifndef soap_read_d__AppSequenceType
#define soap_read_d__AppSequenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__AppSequenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__AppSequenceType * SOAP_FMAC4 soap_get_d__AppSequenceType(struct soap*, struct d__AppSequenceType *, const char*, const char*);

#ifndef SOAP_TYPE_d__SigType
#define SOAP_TYPE_d__SigType (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__SigType(struct soap*, struct d__SigType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__SigType(struct soap*, const struct d__SigType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__SigType(struct soap*, const char*, int, const struct d__SigType *, const char*);
SOAP_FMAC3 struct d__SigType * SOAP_FMAC4 soap_in_d__SigType(struct soap*, const char*, struct d__SigType *, const char*);

#ifndef soap_write_d__SigType
#define soap_write_d__SigType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__SigType(soap, data), 0) || soap_put_d__SigType(soap, data, "d:SigType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__SigType(struct soap*, const struct d__SigType *, const char*, const char*);

#ifndef soap_read_d__SigType
#define soap_read_d__SigType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__SigType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__SigType * SOAP_FMAC4 soap_get_d__SigType(struct soap*, struct d__SigType *, const char*, const char*);

#ifndef SOAP_TYPE_d__SecurityType
#define SOAP_TYPE_d__SecurityType (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__SecurityType(struct soap*, struct d__SecurityType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__SecurityType(struct soap*, const struct d__SecurityType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__SecurityType(struct soap*, const char*, int, const struct d__SecurityType *, const char*);
SOAP_FMAC3 struct d__SecurityType * SOAP_FMAC4 soap_in_d__SecurityType(struct soap*, const char*, struct d__SecurityType *, const char*);

#ifndef soap_write_d__SecurityType
#define soap_write_d__SecurityType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__SecurityType(soap, data), 0) || soap_put_d__SecurityType(soap, data, "d:SecurityType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__SecurityType(struct soap*, const struct d__SecurityType *, const char*, const char*);

#ifndef soap_read_d__SecurityType
#define soap_read_d__SecurityType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__SecurityType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__SecurityType * SOAP_FMAC4 soap_get_d__SecurityType(struct soap*, struct d__SecurityType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ResolveMatchType
#define SOAP_TYPE_d__ResolveMatchType (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ResolveMatchType(struct soap*, struct d__ResolveMatchType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ResolveMatchType(struct soap*, const struct d__ResolveMatchType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ResolveMatchType(struct soap*, const char*, int, const struct d__ResolveMatchType *, const char*);
SOAP_FMAC3 struct d__ResolveMatchType * SOAP_FMAC4 soap_in_d__ResolveMatchType(struct soap*, const char*, struct d__ResolveMatchType *, const char*);

#ifndef soap_write_d__ResolveMatchType
#define soap_write_d__ResolveMatchType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ResolveMatchType(soap, data), 0) || soap_put_d__ResolveMatchType(soap, data, "d:ResolveMatchType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ResolveMatchType(struct soap*, const struct d__ResolveMatchType *, const char*, const char*);

#ifndef soap_read_d__ResolveMatchType
#define soap_read_d__ResolveMatchType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ResolveMatchType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ResolveMatchType * SOAP_FMAC4 soap_get_d__ResolveMatchType(struct soap*, struct d__ResolveMatchType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ResolveMatchesType
#define SOAP_TYPE_d__ResolveMatchesType (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ResolveMatchesType(struct soap*, struct d__ResolveMatchesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ResolveMatchesType(struct soap*, const struct d__ResolveMatchesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ResolveMatchesType(struct soap*, const char*, int, const struct d__ResolveMatchesType *, const char*);
SOAP_FMAC3 struct d__ResolveMatchesType * SOAP_FMAC4 soap_in_d__ResolveMatchesType(struct soap*, const char*, struct d__ResolveMatchesType *, const char*);

#ifndef soap_write_d__ResolveMatchesType
#define soap_write_d__ResolveMatchesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ResolveMatchesType(soap, data), 0) || soap_put_d__ResolveMatchesType(soap, data, "d:ResolveMatchesType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ResolveMatchesType(struct soap*, const struct d__ResolveMatchesType *, const char*, const char*);

#ifndef soap_read_d__ResolveMatchesType
#define soap_read_d__ResolveMatchesType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ResolveMatchesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ResolveMatchesType * SOAP_FMAC4 soap_get_d__ResolveMatchesType(struct soap*, struct d__ResolveMatchesType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ResolveType
#define SOAP_TYPE_d__ResolveType (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ResolveType(struct soap*, struct d__ResolveType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ResolveType(struct soap*, const struct d__ResolveType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ResolveType(struct soap*, const char*, int, const struct d__ResolveType *, const char*);
SOAP_FMAC3 struct d__ResolveType * SOAP_FMAC4 soap_in_d__ResolveType(struct soap*, const char*, struct d__ResolveType *, const char*);

#ifndef soap_write_d__ResolveType
#define soap_write_d__ResolveType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ResolveType(soap, data), 0) || soap_put_d__ResolveType(soap, data, "d:ResolveType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ResolveType(struct soap*, const struct d__ResolveType *, const char*, const char*);

#ifndef soap_read_d__ResolveType
#define soap_read_d__ResolveType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ResolveType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ResolveType * SOAP_FMAC4 soap_get_d__ResolveType(struct soap*, struct d__ResolveType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ProbeMatchType
#define SOAP_TYPE_d__ProbeMatchType (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ProbeMatchType(struct soap*, struct d__ProbeMatchType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ProbeMatchType(struct soap*, const struct d__ProbeMatchType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ProbeMatchType(struct soap*, const char*, int, const struct d__ProbeMatchType *, const char*);
SOAP_FMAC3 struct d__ProbeMatchType * SOAP_FMAC4 soap_in_d__ProbeMatchType(struct soap*, const char*, struct d__ProbeMatchType *, const char*);

#ifndef soap_write_d__ProbeMatchType
#define soap_write_d__ProbeMatchType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ProbeMatchType(soap, data), 0) || soap_put_d__ProbeMatchType(soap, data, "d:ProbeMatchType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ProbeMatchType(struct soap*, const struct d__ProbeMatchType *, const char*, const char*);

#ifndef soap_read_d__ProbeMatchType
#define soap_read_d__ProbeMatchType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ProbeMatchType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatchType * SOAP_FMAC4 soap_get_d__ProbeMatchType(struct soap*, struct d__ProbeMatchType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ProbeMatchesType
#define SOAP_TYPE_d__ProbeMatchesType (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ProbeMatchesType(struct soap*, struct d__ProbeMatchesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ProbeMatchesType(struct soap*, const struct d__ProbeMatchesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ProbeMatchesType(struct soap*, const char*, int, const struct d__ProbeMatchesType *, const char*);
SOAP_FMAC3 struct d__ProbeMatchesType * SOAP_FMAC4 soap_in_d__ProbeMatchesType(struct soap*, const char*, struct d__ProbeMatchesType *, const char*);

#ifndef soap_write_d__ProbeMatchesType
#define soap_write_d__ProbeMatchesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ProbeMatchesType(soap, data), 0) || soap_put_d__ProbeMatchesType(soap, data, "d:ProbeMatchesType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ProbeMatchesType(struct soap*, const struct d__ProbeMatchesType *, const char*, const char*);

#ifndef soap_read_d__ProbeMatchesType
#define soap_read_d__ProbeMatchesType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ProbeMatchesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatchesType * SOAP_FMAC4 soap_get_d__ProbeMatchesType(struct soap*, struct d__ProbeMatchesType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ProbeType
#define SOAP_TYPE_d__ProbeType (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ProbeType(struct soap*, struct d__ProbeType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ProbeType(struct soap*, const struct d__ProbeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ProbeType(struct soap*, const char*, int, const struct d__ProbeType *, const char*);
SOAP_FMAC3 struct d__ProbeType * SOAP_FMAC4 soap_in_d__ProbeType(struct soap*, const char*, struct d__ProbeType *, const char*);

#ifndef soap_write_d__ProbeType
#define soap_write_d__ProbeType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ProbeType(soap, data), 0) || soap_put_d__ProbeType(soap, data, "d:ProbeType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ProbeType(struct soap*, const struct d__ProbeType *, const char*, const char*);

#ifndef soap_read_d__ProbeType
#define soap_read_d__ProbeType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ProbeType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeType * SOAP_FMAC4 soap_get_d__ProbeType(struct soap*, struct d__ProbeType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ByeType
#define SOAP_TYPE_d__ByeType (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ByeType(struct soap*, struct d__ByeType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ByeType(struct soap*, const struct d__ByeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ByeType(struct soap*, const char*, int, const struct d__ByeType *, const char*);
SOAP_FMAC3 struct d__ByeType * SOAP_FMAC4 soap_in_d__ByeType(struct soap*, const char*, struct d__ByeType *, const char*);

#ifndef soap_write_d__ByeType
#define soap_write_d__ByeType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ByeType(soap, data), 0) || soap_put_d__ByeType(soap, data, "d:ByeType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ByeType(struct soap*, const struct d__ByeType *, const char*, const char*);

#ifndef soap_read_d__ByeType
#define soap_read_d__ByeType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ByeType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ByeType * SOAP_FMAC4 soap_get_d__ByeType(struct soap*, struct d__ByeType *, const char*, const char*);

#ifndef SOAP_TYPE_d__ScopesType
#define SOAP_TYPE_d__ScopesType (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ScopesType(struct soap*, struct d__ScopesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ScopesType(struct soap*, const struct d__ScopesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ScopesType(struct soap*, const char*, int, const struct d__ScopesType *, const char*);
SOAP_FMAC3 struct d__ScopesType * SOAP_FMAC4 soap_in_d__ScopesType(struct soap*, const char*, struct d__ScopesType *, const char*);

#ifndef soap_write_d__ScopesType
#define soap_write_d__ScopesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ScopesType(soap, data), 0) || soap_put_d__ScopesType(soap, data, "d:ScopesType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ScopesType(struct soap*, const struct d__ScopesType *, const char*, const char*);

#ifndef soap_read_d__ScopesType
#define soap_read_d__ScopesType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ScopesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ScopesType * SOAP_FMAC4 soap_get_d__ScopesType(struct soap*, struct d__ScopesType *, const char*, const char*);

#ifndef SOAP_TYPE_d__HelloType
#define SOAP_TYPE_d__HelloType (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__HelloType(struct soap*, struct d__HelloType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__HelloType(struct soap*, const struct d__HelloType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__HelloType(struct soap*, const char*, int, const struct d__HelloType *, const char*);
SOAP_FMAC3 struct d__HelloType * SOAP_FMAC4 soap_in_d__HelloType(struct soap*, const char*, struct d__HelloType *, const char*);

#ifndef soap_write_d__HelloType
#define soap_write_d__HelloType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__HelloType(soap, data), 0) || soap_put_d__HelloType(soap, data, "d:HelloType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__HelloType(struct soap*, const struct d__HelloType *, const char*, const char*);

#ifndef soap_read_d__HelloType
#define soap_read_d__HelloType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__HelloType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__HelloType * SOAP_FMAC4 soap_get_d__HelloType(struct soap*, struct d__HelloType *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

/* _wsa__FaultTo is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
#endif

#define soap_default__wsa__FaultTo(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__FaultTo(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__FaultTo soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__FaultTo soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__FaultTo
#define soap_write__wsa__FaultTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__FaultTo(soap, data), 0) || soap_put__wsa__FaultTo(soap, data, "wsa:FaultTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__FaultTo soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__FaultTo
#define soap_read__wsa__FaultTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__FaultTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__FaultTo soap_get_wsa__EndpointReferenceType


/* _wsa__ReplyTo is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
#endif

#define soap_default__wsa__ReplyTo(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__ReplyTo(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__ReplyTo soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__ReplyTo soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__ReplyTo
#define soap_write__wsa__ReplyTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__ReplyTo(soap, data), 0) || soap_put__wsa__ReplyTo(soap, data, "wsa:ReplyTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__ReplyTo soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__ReplyTo
#define soap_read__wsa__ReplyTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__ReplyTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__ReplyTo soap_get_wsa__EndpointReferenceType


/* _wsa__From is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
#endif

#define soap_default__wsa__From(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__From(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__From soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__From soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__From
#define soap_write__wsa__From(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__From(soap, data), 0) || soap_put__wsa__From(soap, data, "wsa:From", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__From soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__From
#define soap_read__wsa__From(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__From(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__From soap_get_wsa__EndpointReferenceType


/* _wsa__RelatesTo is a typedef element/attribute synonym for wsa__Relationship */

#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
#endif

#define soap_default__wsa__RelatesTo(soap, a) soap_default_wsa__Relationship(soap, a)


#define soap_serialize__wsa__RelatesTo(soap, a) soap_serialize_wsa__Relationship(soap, a)


#define soap_out__wsa__RelatesTo soap_out_wsa__Relationship


#define soap_in__wsa__RelatesTo soap_in_wsa__Relationship


#ifndef soap_write__wsa__RelatesTo
#define soap_write__wsa__RelatesTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__RelatesTo(soap, data), 0) || soap_put__wsa__RelatesTo(soap, data, "wsa:RelatesTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__RelatesTo soap_put_wsa__Relationship


#ifndef soap_read__wsa__RelatesTo
#define soap_read__wsa__RelatesTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__RelatesTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__RelatesTo soap_get_wsa__Relationship


/* _wsa__EndpointReference is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
#endif

#define soap_default__wsa__EndpointReference(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__EndpointReference(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__EndpointReference soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__EndpointReference soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__EndpointReference
#define soap_write__wsa__EndpointReference(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__EndpointReference(soap, data), 0) || soap_put__wsa__EndpointReference(soap, data, "wsa:EndpointReference", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__EndpointReference soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__EndpointReference
#define soap_read__wsa__EndpointReference(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__EndpointReference(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__EndpointReference soap_get_wsa__EndpointReferenceType


#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__Relationship(struct soap*, struct wsa__Relationship *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__Relationship(struct soap*, const struct wsa__Relationship *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__Relationship(struct soap*, const char*, int, const struct wsa__Relationship *, const char*);
SOAP_FMAC3 struct wsa__Relationship * SOAP_FMAC4 soap_in_wsa__Relationship(struct soap*, const char*, struct wsa__Relationship *, const char*);

#ifndef soap_write_wsa__Relationship
#define soap_write_wsa__Relationship(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__Relationship(soap, data), 0) || soap_put_wsa__Relationship(soap, data, "wsa:Relationship", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__Relationship(struct soap*, const struct wsa__Relationship *, const char*, const char*);

#ifndef soap_read_wsa__Relationship
#define soap_read_wsa__Relationship(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__Relationship(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__Relationship * SOAP_FMAC4 soap_get_wsa__Relationship(struct soap*, struct wsa__Relationship *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__ServiceNameType(struct soap*, const struct wsa__ServiceNameType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__ServiceNameType(struct soap*, const char*, int, const struct wsa__ServiceNameType *, const char*);
SOAP_FMAC3 struct wsa__ServiceNameType * SOAP_FMAC4 soap_in_wsa__ServiceNameType(struct soap*, const char*, struct wsa__ServiceNameType *, const char*);

#ifndef soap_write_wsa__ServiceNameType
#define soap_write_wsa__ServiceNameType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__ServiceNameType(soap, data), 0) || soap_put_wsa__ServiceNameType(soap, data, "wsa:ServiceNameType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__ServiceNameType(struct soap*, const struct wsa__ServiceNameType *, const char*, const char*);

#ifndef soap_read_wsa__ServiceNameType
#define soap_read_wsa__ServiceNameType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__ServiceNameType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ServiceNameType * SOAP_FMAC4 soap_get_wsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__ReferenceParametersType(struct soap*, const struct wsa__ReferenceParametersType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__ReferenceParametersType(struct soap*, const char*, int, const struct wsa__ReferenceParametersType *, const char*);
SOAP_FMAC3 struct wsa__ReferenceParametersType * SOAP_FMAC4 soap_in_wsa__ReferenceParametersType(struct soap*, const char*, struct wsa__ReferenceParametersType *, const char*);

#ifndef soap_write_wsa__ReferenceParametersType
#define soap_write_wsa__ReferenceParametersType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__ReferenceParametersType(soap, data), 0) || soap_put_wsa__ReferenceParametersType(soap, data, "wsa:ReferenceParametersType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__ReferenceParametersType(struct soap*, const struct wsa__ReferenceParametersType *, const char*, const char*);

#ifndef soap_read_wsa__ReferenceParametersType
#define soap_read_wsa__ReferenceParametersType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__ReferenceParametersType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferenceParametersType * SOAP_FMAC4 soap_get_wsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__ReferencePropertiesType(struct soap*, const struct wsa__ReferencePropertiesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__ReferencePropertiesType(struct soap*, const char*, int, const struct wsa__ReferencePropertiesType *, const char*);
SOAP_FMAC3 struct wsa__ReferencePropertiesType * SOAP_FMAC4 soap_in_wsa__ReferencePropertiesType(struct soap*, const char*, struct wsa__ReferencePropertiesType *, const char*);

#ifndef soap_write_wsa__ReferencePropertiesType
#define soap_write_wsa__ReferencePropertiesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__ReferencePropertiesType(soap, data), 0) || soap_put_wsa__ReferencePropertiesType(soap, data, "wsa:ReferencePropertiesType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__ReferencePropertiesType(struct soap*, const struct wsa__ReferencePropertiesType *, const char*, const char*);

#ifndef soap_read_wsa__ReferencePropertiesType
#define soap_read_wsa__ReferencePropertiesType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__ReferencePropertiesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferencePropertiesType * SOAP_FMAC4 soap_get_wsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__EndpointReferenceType(struct soap*, struct wsa__EndpointReferenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__EndpointReferenceType(struct soap*, const struct wsa__EndpointReferenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__EndpointReferenceType(struct soap*, const char*, int, const struct wsa__EndpointReferenceType *, const char*);
SOAP_FMAC3 struct wsa__EndpointReferenceType * SOAP_FMAC4 soap_in_wsa__EndpointReferenceType(struct soap*, const char*, struct wsa__EndpointReferenceType *, const char*);

#ifndef soap_write_wsa__EndpointReferenceType
#define soap_write_wsa__EndpointReferenceType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__EndpointReferenceType(soap, data), 0) || soap_put_wsa__EndpointReferenceType(soap, data, "wsa:EndpointReferenceType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__EndpointReferenceType(struct soap*, const struct wsa__EndpointReferenceType *, const char*, const char*);

#ifndef soap_read_wsa__EndpointReferenceType
#define soap_read_wsa__EndpointReferenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__EndpointReferenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType * SOAP_FMAC4 soap_get_wsa__EndpointReferenceType(struct soap*, struct wsa__EndpointReferenceType *, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ByeType
#define SOAP_TYPE_PointerTod__ByeType (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ByeType(struct soap*, struct d__ByeType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ByeType(struct soap*, const char *, int, struct d__ByeType *const*, const char *);
SOAP_FMAC3 struct d__ByeType ** SOAP_FMAC4 soap_in_PointerTod__ByeType(struct soap*, const char*, struct d__ByeType **, const char*);

#ifndef soap_write_PointerTod__ByeType
#define soap_write_PointerTod__ByeType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ByeType(soap, data), 0) || soap_put_PointerTod__ByeType(soap, data, "d:ByeType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ByeType(struct soap*, struct d__ByeType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ByeType
#define soap_read_PointerTod__ByeType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ByeType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ByeType ** SOAP_FMAC4 soap_get_PointerTod__ByeType(struct soap*, struct d__ByeType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ResolveType
#define SOAP_TYPE_PointerTod__ResolveType (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ResolveType(struct soap*, struct d__ResolveType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ResolveType(struct soap*, const char *, int, struct d__ResolveType *const*, const char *);
SOAP_FMAC3 struct d__ResolveType ** SOAP_FMAC4 soap_in_PointerTod__ResolveType(struct soap*, const char*, struct d__ResolveType **, const char*);

#ifndef soap_write_PointerTod__ResolveType
#define soap_write_PointerTod__ResolveType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ResolveType(soap, data), 0) || soap_put_PointerTod__ResolveType(soap, data, "d:ResolveType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ResolveType(struct soap*, struct d__ResolveType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ResolveType
#define soap_read_PointerTod__ResolveType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ResolveType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ResolveType ** SOAP_FMAC4 soap_get_PointerTod__ResolveType(struct soap*, struct d__ResolveType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__HelloType
#define SOAP_TYPE_PointerTod__HelloType (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__HelloType(struct soap*, struct d__HelloType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__HelloType(struct soap*, const char *, int, struct d__HelloType *const*, const char *);
SOAP_FMAC3 struct d__HelloType ** SOAP_FMAC4 soap_in_PointerTod__HelloType(struct soap*, const char*, struct d__HelloType **, const char*);

#ifndef soap_write_PointerTod__HelloType
#define soap_write_PointerTod__HelloType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__HelloType(soap, data), 0) || soap_put_PointerTod__HelloType(soap, data, "d:HelloType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__HelloType(struct soap*, struct d__HelloType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__HelloType
#define soap_read_PointerTod__HelloType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__HelloType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__HelloType ** SOAP_FMAC4 soap_get_PointerTod__HelloType(struct soap*, struct d__HelloType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ProbeMatchesType
#define SOAP_TYPE_PointerTod__ProbeMatchesType (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ProbeMatchesType(struct soap*, struct d__ProbeMatchesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ProbeMatchesType(struct soap*, const char *, int, struct d__ProbeMatchesType *const*, const char *);
SOAP_FMAC3 struct d__ProbeMatchesType ** SOAP_FMAC4 soap_in_PointerTod__ProbeMatchesType(struct soap*, const char*, struct d__ProbeMatchesType **, const char*);

#ifndef soap_write_PointerTod__ProbeMatchesType
#define soap_write_PointerTod__ProbeMatchesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ProbeMatchesType(soap, data), 0) || soap_put_PointerTod__ProbeMatchesType(soap, data, "d:ProbeMatchesType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ProbeMatchesType(struct soap*, struct d__ProbeMatchesType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ProbeMatchesType
#define soap_read_PointerTod__ProbeMatchesType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ProbeMatchesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatchesType ** SOAP_FMAC4 soap_get_PointerTod__ProbeMatchesType(struct soap*, struct d__ProbeMatchesType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ProbeType
#define SOAP_TYPE_PointerTod__ProbeType (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ProbeType(struct soap*, struct d__ProbeType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ProbeType(struct soap*, const char *, int, struct d__ProbeType *const*, const char *);
SOAP_FMAC3 struct d__ProbeType ** SOAP_FMAC4 soap_in_PointerTod__ProbeType(struct soap*, const char*, struct d__ProbeType **, const char*);

#ifndef soap_write_PointerTod__ProbeType
#define soap_write_PointerTod__ProbeType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ProbeType(soap, data), 0) || soap_put_PointerTod__ProbeType(soap, data, "d:ProbeType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ProbeType(struct soap*, struct d__ProbeType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ProbeType
#define soap_read_PointerTod__ProbeType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ProbeType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeType ** SOAP_FMAC4 soap_get_PointerTod__ProbeType(struct soap*, struct d__ProbeType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__SigType
#define SOAP_TYPE_PointerTod__SigType (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__SigType(struct soap*, struct d__SigType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__SigType(struct soap*, const char *, int, struct d__SigType *const*, const char *);
SOAP_FMAC3 struct d__SigType ** SOAP_FMAC4 soap_in_PointerTod__SigType(struct soap*, const char*, struct d__SigType **, const char*);

#ifndef soap_write_PointerTod__SigType
#define soap_write_PointerTod__SigType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__SigType(soap, data), 0) || soap_put_PointerTod__SigType(soap, data, "d:SigType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__SigType(struct soap*, struct d__SigType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__SigType
#define soap_read_PointerTod__SigType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__SigType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__SigType ** SOAP_FMAC4 soap_get_PointerTod__SigType(struct soap*, struct d__SigType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ResolveMatchType
#define SOAP_TYPE_PointerTod__ResolveMatchType (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ResolveMatchType(struct soap*, struct d__ResolveMatchType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ResolveMatchType(struct soap*, const char *, int, struct d__ResolveMatchType *const*, const char *);
SOAP_FMAC3 struct d__ResolveMatchType ** SOAP_FMAC4 soap_in_PointerTod__ResolveMatchType(struct soap*, const char*, struct d__ResolveMatchType **, const char*);

#ifndef soap_write_PointerTod__ResolveMatchType
#define soap_write_PointerTod__ResolveMatchType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ResolveMatchType(soap, data), 0) || soap_put_PointerTod__ResolveMatchType(soap, data, "d:ResolveMatchType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ResolveMatchType(struct soap*, struct d__ResolveMatchType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ResolveMatchType
#define soap_read_PointerTod__ResolveMatchType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ResolveMatchType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ResolveMatchType ** SOAP_FMAC4 soap_get_PointerTod__ResolveMatchType(struct soap*, struct d__ResolveMatchType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ProbeMatchType
#define SOAP_TYPE_PointerTod__ProbeMatchType (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ProbeMatchType(struct soap*, struct d__ProbeMatchType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ProbeMatchType(struct soap*, const char *, int, struct d__ProbeMatchType *const*, const char *);
SOAP_FMAC3 struct d__ProbeMatchType ** SOAP_FMAC4 soap_in_PointerTod__ProbeMatchType(struct soap*, const char*, struct d__ProbeMatchType **, const char*);

#ifndef soap_write_PointerTod__ProbeMatchType
#define soap_write_PointerTod__ProbeMatchType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ProbeMatchType(soap, data), 0) || soap_put_PointerTod__ProbeMatchType(soap, data, "d:ProbeMatchType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ProbeMatchType(struct soap*, struct d__ProbeMatchType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ProbeMatchType
#define soap_read_PointerTod__ProbeMatchType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ProbeMatchType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatchType ** SOAP_FMAC4 soap_get_PointerTod__ProbeMatchType(struct soap*, struct d__ProbeMatchType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTounsignedInt
#define SOAP_TYPE_PointerTounsignedInt (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedInt(struct soap*, unsigned int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedInt(struct soap*, const char *, int, unsigned int *const*, const char *);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_in_PointerTounsignedInt(struct soap*, const char*, unsigned int **, const char*);

#ifndef soap_write_PointerTounsignedInt
#define soap_write_PointerTounsignedInt(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTounsignedInt(soap, data), 0) || soap_put_PointerTounsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedInt(struct soap*, unsigned int *const*, const char*, const char*);

#ifndef soap_read_PointerTounsignedInt
#define soap_read_PointerTounsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_get_PointerTounsignedInt(struct soap*, unsigned int **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__ScopesType
#define SOAP_TYPE_PointerTod__ScopesType (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ScopesType(struct soap*, struct d__ScopesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ScopesType(struct soap*, const char *, int, struct d__ScopesType *const*, const char *);
SOAP_FMAC3 struct d__ScopesType ** SOAP_FMAC4 soap_in_PointerTod__ScopesType(struct soap*, const char*, struct d__ScopesType **, const char*);

#ifndef soap_write_PointerTod__ScopesType
#define soap_write_PointerTod__ScopesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ScopesType(soap, data), 0) || soap_put_PointerTod__ScopesType(soap, data, "d:ScopesType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ScopesType(struct soap*, struct d__ScopesType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ScopesType
#define soap_read_PointerTod__ScopesType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ScopesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ScopesType ** SOAP_FMAC4 soap_get_PointerTod__ScopesType(struct soap*, struct d__ScopesType **, const char*, const char*);

#ifndef SOAP_TYPE_d__FaultCodeOpenType
#define SOAP_TYPE_d__FaultCodeOpenType (47)
#endif

#define soap_default_d__FaultCodeOpenType(soap, a) soap_default_string(soap, a)


#define soap_serialize_d__FaultCodeOpenType(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__FaultCodeOpenType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_d__FaultCodeOpenType(struct soap*, const char*, char **, const char*);

#ifndef soap_write_d__FaultCodeOpenType
#define soap_write_d__FaultCodeOpenType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__FaultCodeOpenType(soap, data), 0) || soap_put_d__FaultCodeOpenType(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__FaultCodeOpenType(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_d__FaultCodeOpenType
#define soap_read_d__FaultCodeOpenType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__FaultCodeOpenType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_d__FaultCodeOpenType(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_d__UriListType
#define SOAP_TYPE_d__UriListType (46)
#endif

#define soap_default_d__UriListType(soap, a) soap_default_string(soap, a)


#define soap_serialize_d__UriListType(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__UriListType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_d__UriListType(struct soap*, const char*, char **, const char*);

#ifndef soap_write_d__UriListType
#define soap_write_d__UriListType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__UriListType(soap, data), 0) || soap_put_d__UriListType(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__UriListType(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_d__UriListType
#define soap_read_d__UriListType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__UriListType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_d__UriListType(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_d__QNameListType
#define SOAP_TYPE_d__QNameListType (45)
#endif

#define soap_default_d__QNameListType(soap, a) soap_default_string(soap, a)


#define soap_serialize_d__QNameListType(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__QNameListType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_d__QNameListType(struct soap*, const char*, char **, const char*);

#ifndef soap_write_d__QNameListType
#define soap_write_d__QNameListType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__QNameListType(soap, data), 0) || soap_put_d__QNameListType(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__QNameListType(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_d__QNameListType
#define soap_read_d__QNameListType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__QNameListType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_d__QNameListType(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_d__OpenRelationshipType
#define SOAP_TYPE_d__OpenRelationshipType (44)
#endif

#define soap_default_d__OpenRelationshipType(soap, a) soap_default_string(soap, a)


#define soap_serialize_d__OpenRelationshipType(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__OpenRelationshipType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_d__OpenRelationshipType(struct soap*, const char*, char **, const char*);

#ifndef soap_write_d__OpenRelationshipType
#define soap_write_d__OpenRelationshipType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__OpenRelationshipType(soap, data), 0) || soap_put_d__OpenRelationshipType(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__OpenRelationshipType(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_d__OpenRelationshipType
#define soap_read_d__OpenRelationshipType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__OpenRelationshipType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_d__OpenRelationshipType(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__IDREFS
#define SOAP_TYPE_xsd__IDREFS (43)
#endif

#define soap_default_xsd__IDREFS(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__IDREFS(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__IDREFS(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__IDREFS(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__IDREFS
#define soap_write_xsd__IDREFS(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__IDREFS(soap, data), 0) || soap_put_xsd__IDREFS(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__IDREFS(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__IDREFS
#define soap_read_xsd__IDREFS(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__IDREFS(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__IDREFS(struct soap*, char **, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_wsa__FaultTo
#define SOAP_TYPE_PointerTo_wsa__FaultTo (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__FaultTo(struct soap*, struct wsa__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__FaultTo(struct soap*, const char *, int, struct wsa__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa__FaultTo(struct soap*, const char*, struct wsa__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa__FaultTo
#define soap_write_PointerTo_wsa__FaultTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__FaultTo(soap, data), 0) || soap_put_PointerTo_wsa__FaultTo(soap, data, "wsa:FaultTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__FaultTo(struct soap*, struct wsa__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__FaultTo
#define soap_read_PointerTo_wsa__FaultTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__FaultTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa__FaultTo(struct soap*, struct wsa__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__ReplyTo
#define SOAP_TYPE_PointerTo_wsa__ReplyTo (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__ReplyTo(struct soap*, struct wsa__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__ReplyTo(struct soap*, const char *, int, struct wsa__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa__ReplyTo(struct soap*, const char*, struct wsa__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa__ReplyTo
#define soap_write_PointerTo_wsa__ReplyTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__ReplyTo(soap, data), 0) || soap_put_PointerTo_wsa__ReplyTo(soap, data, "wsa:ReplyTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__ReplyTo(struct soap*, struct wsa__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__ReplyTo
#define soap_read_PointerTo_wsa__ReplyTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__ReplyTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa__ReplyTo(struct soap*, struct wsa__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__From
#define SOAP_TYPE_PointerTo_wsa__From (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__From(struct soap*, struct wsa__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__From(struct soap*, const char *, int, struct wsa__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa__From(struct soap*, const char*, struct wsa__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa__From
#define soap_write_PointerTo_wsa__From(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__From(soap, data), 0) || soap_put_PointerTo_wsa__From(soap, data, "wsa:From", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__From(struct soap*, struct wsa__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__From
#define soap_read_PointerTo_wsa__From(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__From(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa__From(struct soap*, struct wsa__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__RelatesTo
#define SOAP_TYPE_PointerTo_wsa__RelatesTo (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__RelatesTo(struct soap*, struct wsa__Relationship *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__RelatesTo(struct soap*, const char *, int, struct wsa__Relationship *const*, const char *);
SOAP_FMAC3 struct wsa__Relationship ** SOAP_FMAC4 soap_in_PointerTo_wsa__RelatesTo(struct soap*, const char*, struct wsa__Relationship **, const char*);

#ifndef soap_write_PointerTo_wsa__RelatesTo
#define soap_write_PointerTo_wsa__RelatesTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__RelatesTo(soap, data), 0) || soap_put_PointerTo_wsa__RelatesTo(soap, data, "wsa:RelatesTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__RelatesTo(struct soap*, struct wsa__Relationship *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__RelatesTo
#define soap_read_PointerTo_wsa__RelatesTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__RelatesTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__Relationship ** SOAP_FMAC4 soap_get_PointerTo_wsa__RelatesTo(struct soap*, struct wsa__Relationship **, const char*, const char*);

/* _wsa__Action is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
#endif

#define soap_default__wsa__Action(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa__Action(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa__Action soap_out_string


#define soap_in__wsa__Action soap_in_string


#ifndef soap_write__wsa__Action
#define soap_write__wsa__Action(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__Action(soap, data), 0) || soap_put__wsa__Action(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__Action soap_put_string


#ifndef soap_read__wsa__Action
#define soap_read__wsa__Action(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__Action(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__Action soap_get_string


/* _wsa__To is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
#endif

#define soap_default__wsa__To(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa__To(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa__To soap_out_string


#define soap_in__wsa__To soap_in_string


#ifndef soap_write__wsa__To
#define soap_write__wsa__To(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__To(soap, data), 0) || soap_put__wsa__To(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__To soap_put_string


#ifndef soap_read__wsa__To
#define soap_read__wsa__To(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__To(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__To soap_get_string


/* _wsa__MessageID is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
#endif

#define soap_default__wsa__MessageID(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa__MessageID(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa__MessageID soap_out_string


#define soap_in__wsa__MessageID soap_in_string


#ifndef soap_write__wsa__MessageID
#define soap_write__wsa__MessageID(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__MessageID(soap, data), 0) || soap_put__wsa__MessageID(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__MessageID soap_put_string


#ifndef soap_read__wsa__MessageID
#define soap_read__wsa__MessageID(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__MessageID(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__MessageID soap_get_string


#ifndef SOAP_TYPE_PointerTowsa__ServiceNameType
#define SOAP_TYPE_PointerTowsa__ServiceNameType (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa__ServiceNameType(struct soap*, const char *, int, struct wsa__ServiceNameType *const*, const char *);
SOAP_FMAC3 struct wsa__ServiceNameType ** SOAP_FMAC4 soap_in_PointerTowsa__ServiceNameType(struct soap*, const char*, struct wsa__ServiceNameType **, const char*);

#ifndef soap_write_PointerTowsa__ServiceNameType
#define soap_write_PointerTowsa__ServiceNameType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa__ServiceNameType(soap, data), 0) || soap_put_PointerTowsa__ServiceNameType(soap, data, "wsa:ServiceNameType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa__ServiceNameType
#define soap_read_PointerTowsa__ServiceNameType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa__ServiceNameType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ServiceNameType ** SOAP_FMAC4 soap_get_PointerTowsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_QName
#define SOAP_TYPE_PointerTo_QName (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_QName(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_QName(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTo_QName(struct soap*, const char*, char ***, const char*);

#ifndef soap_write_PointerTo_QName
#define soap_write_PointerTo_QName(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_QName(soap, data), 0) || soap_put_PointerTo_QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_QName(struct soap*, char **const*, const char*, const char*);

#ifndef soap_read_PointerTo_QName
#define soap_read_PointerTo_QName(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTo_QName(struct soap*, char ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTowsa__ReferenceParametersType
#define SOAP_TYPE_PointerTowsa__ReferenceParametersType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa__ReferenceParametersType(struct soap*, const char *, int, struct wsa__ReferenceParametersType *const*, const char *);
SOAP_FMAC3 struct wsa__ReferenceParametersType ** SOAP_FMAC4 soap_in_PointerTowsa__ReferenceParametersType(struct soap*, const char*, struct wsa__ReferenceParametersType **, const char*);

#ifndef soap_write_PointerTowsa__ReferenceParametersType
#define soap_write_PointerTowsa__ReferenceParametersType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa__ReferenceParametersType(soap, data), 0) || soap_put_PointerTowsa__ReferenceParametersType(soap, data, "wsa:ReferenceParametersType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa__ReferenceParametersType
#define soap_read_PointerTowsa__ReferenceParametersType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa__ReferenceParametersType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferenceParametersType ** SOAP_FMAC4 soap_get_PointerTowsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTowsa__ReferencePropertiesType
#define SOAP_TYPE_PointerTowsa__ReferencePropertiesType (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa__ReferencePropertiesType(struct soap*, const char *, int, struct wsa__ReferencePropertiesType *const*, const char *);
SOAP_FMAC3 struct wsa__ReferencePropertiesType ** SOAP_FMAC4 soap_in_PointerTowsa__ReferencePropertiesType(struct soap*, const char*, struct wsa__ReferencePropertiesType **, const char*);

#ifndef soap_write_PointerTowsa__ReferencePropertiesType
#define soap_write_PointerTowsa__ReferencePropertiesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa__ReferencePropertiesType(soap, data), 0) || soap_put_PointerTowsa__ReferencePropertiesType(soap, data, "wsa:ReferencePropertiesType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa__ReferencePropertiesType
#define soap_read_PointerTowsa__ReferencePropertiesType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa__ReferencePropertiesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferencePropertiesType ** SOAP_FMAC4 soap_get_PointerTowsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
